name: Daily API Tests

on:
  schedule:
    - cron: '0 8 * * *'  # Runs at 8AM UTC every day
  workflow_dispatch:

jobs:
  run-api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install requests
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run API tests
      run: python api_tests.py
